### ISSUE TITLE
Ignore ".idea" Directory

### ISSUE THREAD

**Issue by loganfranken** [mdkerner/CampusRemoteTour#6]
There's an ".idea" directory that I think is specific to the JetBrains editor. This should be removed from source control and added to a .gitignore list since it's user-specific

**Comment by mdkerner** [comment]
Awesome dude! I'm going to see if I can rustle up some time to work on this project this weekend. 

What ultimately do you want this to end up being? The original idea was just making a really general use framework for creating useful local interactive maps, which I think it does rather well. 
Things I've been thinking about for our campus version:

Hosting ( somewhere.sa.ucsb.edu )?
Feature for users/admins to CRUD map location data( pins, videos, images, etc )?
Repository for said data?
Customizable Data sets(students- food, building names, admin office locations; visitors- landmarks, art pieces, visitor center; upcoming events- A&E stuff, concerts, athletics)?

**Comment by loganfranken** [comment]
@mdkerner It's ultimately up to you since you're the owner of this project. :wink:

I'm just interested in creating a full-featured campus map for UCSB (which could then be used for other campuses), but I'm open to wherever you want to take this.

Maybe create separate issues for each of those questions so we can hash them out individually?

**Comment by mdkerner** [comment]
I created a new issue to discuss just this! 

https://github.com/mdkerner/CampusRemoteTour/issues/8
